---
title: "预测COVID-19的全球扩散——基于Logistic模型和SEIR模型"
author:
  - 肖世莺
  - 张红丽
  - 成宏媛
  - 王瑜
documentclass: ctexart
geometry: "left=2.5cm,right=2cm,top=3cm,bottom=2.5cm"
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: no
classoption: "hyperref,"
---

# 研究背景

COVID-19是一项重大的公共卫生事件。尽管各国政府采取了各种措施来保护城市或国家，例如交通限制、旅行者隔离要求、接触者追踪等，但大规模的全球人口流动已经引起该疾病的迅速传播，使其在全世界蔓延。疫情在中国得到控制的同时，COVID-19的全球传播已造成在亚洲、欧洲、中东和北美激增。截至2020年3月11日，随着全球疫情风险的不断增加，在114个国家中已经有超过118,000例病例，并有4,291人丧生，WHO将COVID-19认定为“大流行”。

随着150多个国家和地区发的病例数量不断增加，建立COVID-19的传播动力学模型并估计其发展趋势对于为政策制定者提供决策支持显得至关重要。数学模型被广泛用于评估流行病传播、预测疾病传播趋势以及提供最佳干预策略和控制措施。近期大量研究争相估计COVID-19的规模和严重程度，一些数学模型和预测方法试图估计COVID-19的传播趋势。大多数研究聚焦于估计基本传染数$R_0$，这是评估COVID-19传播潜力的关键参数。但是，就模型结构和输入参数而言，不同的模型通常会得出不同的结论。当务之急是提高对COVID-19的早期预测和预警能力。

面对这一新传染病及其具有许多未知因素的复杂特征，单一的模型估计可能会得出有偏的结果，因此，我们试图通过比较不同模型的结果来进行全面的严格估计。为了实现客观的估计，我们研究并实施了两种最常用的方法和一种扩展方法：Logistic模型、SEIR模型和改进的SEIR模型。对于降低COVID-19的继发感染风险而采取的干预措施，各国的开始实施时间和水平不同。我们比较了考虑或不考虑这些影响的模型，预测了流行病的传播扩散，并试图比较3种不同模型的不同建议。

# 方法

我们收集了分布在三大洲的8个高风险国家COVID-19的疫情情况，并在不同参数设置的场景下，将Logistic模型和SEIR模型的预测结果进行了比较。数据来自约翰霍普金斯大学系统科学与工程中心（CSSE）运营的COVID-19全球数据库。我们利用2020年1月23日至3月20日的现有报告数据，对不同国家或地区的COVID-19动态进行观测、参数估计和预测。

## Logistic增长模型和参数估计

在场景1中，我们假设流行病趋势服从Logistic增长曲线。我们使用Logistic模型来预测疾病的发展趋势。Logistic模型的本质是曲线拟合，其预测结果高度依赖于历史数据。在以往的研究中，它常被用于流行病的动态预测。在数学方面，Logistic模型描述受增长率和人口容量控制的受感染个体的动态演化。根据下面的常微分方程(1)，我们将得到Logistic函数(2)，该模型描述了受增长率$r$和$P_0$控制的确诊病例数$P$的动态演化，$P_0$是当$T=0$时确诊病例数的初始值。在该模型中确诊病例的最大值为$K$，是通过增加到$P(t)$的最终值可以达到的极限。我们采用OLS拟合Logistic增长函数，预测未来确诊病例的数量。由于早期报告的确诊病例数量通常不准确或缺失，因此将模型的起始日期设置为达到第100个确诊病例的日期。

$$\frac{dP}{dt}=rP(1-\frac{P}{K})\tag{1}$$

$$P(t)=\frac{KP_0 e^{rt}}{K+P_0 (e^{rt}-1)}\tag{2}$$

为了评估Logistic模型预测COVID-19疫情的能力，自达到第100例确诊病例当天开始，每隔10天拟合一次Logistic曲线，每次进行7天预测并使用报告的数据进行评估。对于实验分析，每一次预测，我们都会得到不同的结果误差（如附录A所示）。随着确诊病例数的增加，预计接下来7天的感染数以及未来的峰值大小和峰值时间都在不断变化。此外，由于新的感染爆发、控制措施的实施、公众行为等外部影响，曲线的形状可能会发生变化。

## SEIR模型和参数估计

基于COVID-19感染的流行病学特征，更通常采用SEIR模型来研究这种疾病的动态。SEIR是确定性的人口传播模型，它假设在同一隔间中的每个个体具有相同的特征，因此将人群中的每个个体模拟为一个独立的隔间。但是，通过不同的参数设置，模型得出的结果不同，我们将结果进行了比较，以观察两种不同场景COVID-19的传播模式，即基本SEIR（场景2：无任何干预和措施）和改进的SEIR（场景3：有严格的干预措施）。

在场景2中，我们仅使用基本SEIR模型，并将人群分为四类：易感者（$S$），潜伏者（$E$），感染者（$I$）和移出者（$R$）。SEIR模型的实质是一个关于时间的常微分方程组。它预测的疾病趋势仅取决于参数和开始时间。该模型是通过以下等式测得的，并且假设所有人都没有针对COVID-19的免疫力，因此整个人群最初都容易受到影响，最初的病例数是从报告的数据中收集的。由于在新的疫情爆发初期仍然缺乏可靠的数据，模型的起始日期被设定为每个国家出现第100例确诊病例以来的日期，这表明8个观察到的国家的起始日期不同。

$$\frac{dS}{dt}=-\frac{\beta SI}{N}$$

$$\frac{dE}{dt}=-\frac{\beta SI}{N}-\sigma E$$

$$\frac{dI}{dt}=\sigma E-\gamma I$$

$$\frac{dR}{dt}=\gamma I$$

其中$S$、$E$、$I$、$R$、$N$分别是易感人群、潜伏人群、感染人群、康复者或病亡者、总人口的数量。$\beta=k*b$是受感染者接触的人群$k$和传播概率$b$的乘积。$\gamma=\frac{1}{D}$是感染人群的平均康复或死亡率，其中$D$是感染的平均持续时间，$\sigma$是潜伏者个体发展为感染者的转化率。
 
在场景3中，考虑到公共卫生干预因素对传染病动态的影响，例如政府封锁城市、采取措施来跟踪和隔离与确诊病例有密切接触的人、提倡公民保持社会距离并勤洗手等，我们进一步将改进的SEIR模型用于COVID-19估计。该模型考虑了COVID-19传播的接触率和隔离比例，并将种群分为七个类别：易感者、潜伏者、感染者、移出者、已隔离的易感者、已隔离的潜伏者和已隔离的感染者。将隔离的易感者记为$Sq$，将被隔离的潜伏者记为$Eq$。详细的方程式和参数定义如下：

$$\frac{dS}{dt}=-[c\beta +cq(1-\beta)]S(I+\theta E)+\lambda S_q$$

$$\frac{dE}{dt}=c\beta (1-q)S(I+\theta E)-\sigma E$$

$$\frac{dI}{dt}=\sigma E-(\delta_I+\alpha +\gamma_I)I$$

$$\frac{dS_q}{dt}=(1-\beta)cqS(I+\theta E)-\lambda S_q$$

$$\frac{dE_q}{dt}=\beta cqS(I+\theta E)-\delta_qE_q$$

$$\frac{dH}{dt}=\delta_II+\delta_qE_q-(\alpha+\gamma_H)H$$

$$\frac{dR}{dt}=\gamma_II+\gamma_HH$$

尽管通过实施多种不同的控制措施，各国都减少了人们的社会接触，但我们以接触率和隔离比例作为模型参数进行了初步估算。此外，由于在一段时期的病例数增加之后检疫和控制措施才生效，通常已经激增到相当数量，因此，在改进的模型中使用的8个观察国家的起始日期不同，它们被定义为各国政府宣布对大规模人口采取严格的干预措施和控制措施的日期。

我们认为，由于政府实施了严格的控制措施，接触率有所下降。根据我们先前的相关研究，大规模干预开始后的接触率$c$低于8。每个国家的初始人口都是从已发布的数据中获取的，初始的感染者、康复者的人数是根据报告的数据确定的。模型参数是在拟合初始数据的基础上估算得来的，而每个国家每次接触的传播概率是根据蒙特卡洛模拟的基础上使用每个国家的早期数据估算的。根据WHO报告，我们假设中位潜伏期为5-6天（介于0-14天之间），未感染的易感人群的初始检疫比例为人口的60％〜80％（假设严格的检疫政策是大规模执行），将隔离期设为28天，死亡率是根据每个国家或地区的报告数据得出的。基于以上假设，我们应用了改进的SEIR模型以获得最小估计。

## 传播潜力评估

为了揭示每个国家的疫情潜在增长速度，我们使用了两个参数进行估计。一个是Logistic曲线的增长率（该增长率越大，曲线增长就越快），另一个是基本传染数$R_0$。我们使用了下一代矩阵推导出的基本传染数公式如下：

$$R_0=\frac{\beta}{\gamma}=\frac{k*b}{1/D}$$

其中$\beta$是$(k)$和$b$的乘积，$(k)$是与确诊人员进行接触的人数，$b$是接触后可能感染的概率。$\gamma=1/D$是感染人群中恢复健康或者死亡的平均比率，$D$是感染的平均持续时间。根据COVID-19疫情的相关研究$^{[7]}$中的假设，将$D=7$来获得$R_0$的估计值。

# 结论

## COVID-19疫情进展

我们绘制八个海外国家的疫情曲线来辅助预测全球疫情趋势，并揭示了不同国家的疫情传播模式。这些国家（包括意大利、韩国、伊朗、法国等）的病例迅速上升。疫情曲线如图1所示，曲线的起始日期定为自8个国家达到第100例确诊病例以来的最早日期，即2020年2月20日（韩国，其他国家或地区的起始日期可以在附录B中找到）。由于疫情曲线遵循先升后降的规律，但在我们观察到的时期内，这8个国家都处于快速上升阶段，尚未达到高峰和下降阶段。在这些国家中，意大利确诊患者的数量最多。经过一连串的紧急预防和控制措施后，韩国确诊病例的数量缓慢增加。截至3月20日，伊朗、德国、西班牙和美国约有2万名确诊患者，并且没有放缓的趋势。伊朗有更多的轻度患者，因此治愈率更高。截至3月20日，日本的确诊病例数为963，治愈病例数为191，是这8个国家中病例数最少的国家。

在图2中，截至3月20日，意大利因COVID-19造成的死亡人数达到4032人，意大利的死亡率达到8.57%。伊朗早期的疏忽也导致了其早期40%的高死亡率。一些国家的死亡率也很高，比如美国和日本。而韩国和德国将死亡率控制在1%左右，这是一个积极的迹象。

## 模型预测

在对三个预测模型的比较，关于COVID-19疫情的发展，文章中有不同的结果，如表1（截止到2020.3.20）和表2所示。由于不同的模型建立在不同的理论和假设上，其输出测量值也不同，其中累计数为logistic模型，active数为SEIR模型。从结果中可以看出三种数理模型的差异，并进一步展示了在不考虑干预的情况下的预测差异。

当对比三种预测模型的结果时，关于COVID-19的疫情发展，我们获得了截然不同的结果，如表1（截至2020年3月20日）和表2所示。由于不同的模型基于不同的理论和假设，其输出测量值也不同，其中累计数为Logistic模型，有效数通过SEIR模型进行度量。结果揭示了三种数理模型的差异，并且进一步揭示了在不考虑干预措施的情况下的预测差异。

在场景1中，基于Logistic模型，我们对8个国家的疫情发展趋势进行预测，表1和附录B详细地列出了8个国家的预测结果和增长轨迹。例如，该模型将意大利的感染高峰时间设定在2020年2月23日开始后的50天，最多感染人数为97442人。

基于Logistic模型根据目前报道的数据是无法预测美国的感染人数，因为其呈现为指数增长，难以拟合Logistic曲线，这也表明了美国正处于疫情迅速传播的阶段。

在场景2中，基础SEIR模型结果表示，如果没有任何控制和干预措施，确诊病例会在9-22个月（275-650天）后到达顶峰，在经历如此长时间的疫情扩散后，大多数人最终都会被感染。附录C列出了不同国家的基本SEIR模型预测的详细结果。此外，高峰期的活跃病例数量将达到这些国家人口的10-20%左右，使得医疗系统不堪重负，这是最糟糕的情况，如表2所示。

在场景3中，改进的SEIR模型结果表明，在严格的控制措施下，8个国家的确诊人数将在起始日（达到第100例确诊病例）后的16-32天（从2020年的4月上旬到4月中旬）内达到高峰。附录D显示了8个国家经调整的SEIR模型预测的详细结果。在疫情初期，日本和韩国就采取了相应的隔离措施，其峰值较低且感染者的累积人数相对较少。特别是在日本，我们的预测峰值小于1560，这表明疫情在早期得到了很好的控制。除此之外，从现有数据来看，欧洲国家和美国仍处于疫情爆发阶段，情势不容乐观。改进的SEIR模型预测，西班牙、意大利、德国、法国等国的峰值在10420至85750之间。

根据我们的参数估计方法，我们揭示了疫情确诊人数的动态变化。场景3的估计是基于严格的隔离假设，结果表明，实施控制措施可以显著降低疫情高峰，并使得推动高峰的出现。接触率是影响控制措施效果的重要因素，通过制定和实施严格的防疫措施来降低接触率，从而减小疫情规模，降低疫情峰值。然而，疫情在峰值过后仍然存在很长的拖尾性，我们研究发现，这种拖尾性可以通过延长易感者的隔离时间来减少。

## 传播潜力

Logistic曲线的增长率也被列为传播潜力指数，用于比较表3中的8个国家。我们的结果表明，除了日本（日本的传播速度有所放缓）以外，这些国家在疫情快速传播方面都具有很高的风险。根据以往的传染病动力学研究，已记录的COVID-19的基本传染数$R_0$范围为2.0至4.9。 我们估计的$R_0$范围在1.687〜3.864之间（根据COVID-19研究报告，假设平均感染期为7天）。

# 讨论

根据COVID-19数据跟踪，这8个国家已经推迟了疫情的预防阶段，并进入了疫情爆发阶段。 死亡率分析表明，一些国家可能发生了未发现的疫情感染事件。这8个国家中有7个国家的$R_0$水平高于3，这值得我们注意。

据报道，高死亡率的主要原因是未被发现的病例可能是无症状的或缺乏检测试剂盒。我们的场景2和场景3分别基于最大假设（没有任何干预）和最小假设（有严格干预）。在场景3中，改进的模型表明，假设感染者得到及时检测和统计，严格执行两轮14天的大规模隔离后，疫情的高峰时间即将到来。如表1所示，数据表明日本和韩国的疫情规模减少朝向积极。但是，考虑到各国文化和医疗卫生状况不同，政策和控制措施的实施水平也不同，因此，这些国家的实际情况应介于场景2和场景3之间。值得指出的是，与不采取干预措施相比，如果政府采取严格的控制措施以减少人口流动，实施及时诊断和隔离，峰值时间将在30天左右达到，峰值规模将大大降低到一个相对较低的水平，这最好在疫情的早期触发。但是，疫情会维持几个月直到有疫苗可用。相反，只要疫情没有结束，如果政府放宽干预措施，使人们回到社会距离较近的地方，未来仍有可能爆发疫情。

传播潜力的结果表明，COVID-19的$R_0$值与SARS病毒（$R_0$值在2.0到5.018之间）相似，比流感病毒H1N1（$R_0$值在1.2到3.719之间）和埃博拉病毒（$R_0$值在1.34到3.6520之间）高。COVID-19是一种具有高度传染性的人传人疾病。与政府实施控制措施后的初期相比，预计$R_0$会大大降低，但是，无论每个国家执行哪种政策，每种政策在防疫COVID-19方面都有其局限性，并且疫情会一直持续直到疫苗的出现或者病毒随季节或群体免疫而消失。因此，追踪所有疫情事件是当前阶段控制COVID-19的最关键问题，因为在本地任何未被发现的病例都可以开始新的疫情传播链，此外，公众还应采取适当的防护措施抵抗COVID-19的传播。

从数理模型的角度来看，SEIR模型是用来估计传染病的，而Logistic增长模型是用来拟合曲线发展的。与SEIR模型相比，Logistic模型可以更好地拟合已有数据，因为它是经过现有数据训练的，但是无法准确地判断和融合传染特征。因此，我们认为，Logistic增长模型的短期预测更好。另一方面，SEIR模型通过考虑多人群的相互作用和关联，引入了更多的变量和因素，比Logistic模型更符合传染病发展规律，但是在考虑不同的干预措施时，预测结果会有很大差异。

这项研究有一些局限性。数理模型通过快速合并多个输入以产生预测结果。但是，这一过程涉及到对不确定因素的假设，例如，很难准确地确定人们遵守当地政府的检疫政策或措施的程度，以及可能影响实际接触率和随后的接触率的公共行为，如洗手、带口罩、社交距离等。这些模型也缺乏足够的数据来估计特定人群的隔离比例。实际上，传染病的演变是相当复杂的，我们的研究只考虑了几个因素。此外，缺少检测试剂盒意味着在一些国家许多病例没有进行检测，如果没有强有力的检测，官方的疫情数据是不完整的。当使用不完整的数据时，一个因素中的一个小误差可能会产生巨大的影响。

总之，我们的研究表明，降低接触率是控制早期疾病传播的关键措施，实施足够的隔离期将减少峰值的病例规模。因此，在COVID-19的早期扩散阶段实施强有力的遏制政策并降低峰值以避免医疗体系超负荷，应被列为高风险国家或地区的主要行动。在严格的隔离期过后，政府仍然需要提高公众的预防意识，采取自我保护的行为，使这一传染病事件控制到只有零星的几个。
